### ISSUE TITLE
Code in AbortExtended enum

### ISSUE THREAD

**Issue by BrettRToomey** [nodes-vapor/error-extended#1]
Everything looks good so far! I just had one question. If I remember correctly, we want to be able to pass in custom (other than just status) error codes into our enumerations. Is that correct, @Casperhr?

Something like:
```swift
case badRequest(code: Int, metadata: Node)
```

Vapor's base error enumeration's implementation returns the same value for code as the status code because we weren't allowed to break public APIs and there was no way to pass any information other than a status code.

**Comment by Casperhr** [comment]
@BrettRToomey @steffendsommer correct, make sure there is argument for code: Int = 0
